# Generated by Django 4.2.3 on 2023-07-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentverifyengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
