# Generated by Django 4.2.3 on 2023-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentverifyengine', '0002_company_contact_phone_company_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('roll_number', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
    ]
