# Generated by Django 4.2.3 on 2023-07-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentverifyengine', '0003_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
